### ISSUE TITLE
IMPORT PROJECT

### ISSUE THREAD

**Issue by rufius97** [mlieshoff/jcrapi#127]
When importing project to Eclipse it says `The method getStatusCode() is undefined for the type CrawlerException`

**Comment by mlieshoff** [comment]
How you import? Please check the dependencies.

**Comment by mlieshoff** [comment]
Closed this issue, because jcrapi was not correct imported to the project. @rufius97 if you import it manually, please check the ```pom.xml``` dependencies, which libraries you also need.
