### ISSUE TITLE
displayLevel field

### ISSUE THREAD

**Issue by rtsketo** [mlieshoff/jcrapi#161]
As of now for example for a maxed Epic card, Card.getMaxLevel() returns 13 and Card.getLeve() returns 8.
There's a field in the CRAPI named displayLevel that does contain the current card level as 13.

My suggestion is the implementation of Card.getDisplayLevel() method.

PS. There are also some other fields you might want to implement, like minLevel, requiredForUpgrade, etc.

**Comment by mlieshoff** [comment]
https://github.com/mlieshoff/jcrapi/pull/167
