### ISSUE TITLE
Where is getProfiles function?

### ISSUE THREAD

**Issue by cbalmeida** [mlieshoff/jcrapi#4]
Please provide  `List<Profile> getProfiles(List<String> tags)` function!

Thx!

**Comment by mlieshoff** [comment]
Hi, please try one of:

https://bintray.com/mlieshoff/maven/jcrapi/4.0.3-RC1.1
https://bintray.com/mlieshoff/maven/jcrapi/4.0.2-RC1.2

**Comment by cbalmeida** [comment]
Worked perfectly. Thanks, man!
