### ISSUE TITLE
Suddenly stopped working in Android (was working until thursday)

### ISSUE THREAD

**Issue by Guiaki** [mlieshoff/jcrapi#88]
I was making an Android App testing this wrapper, it was working correctly, the last I can recall is Thursday, suddenly without any change to the App, it stopped working, I tried to debug the code and it simply doesn't do anything after "api.getProfile", here is the code:

```
public class MainActivity extends AppCompatActivity {

    private class myTask extends AsyncTask<Void, Void, Void> {
        Profile profile;
        String devKey = "INSERT_KEY_HERE";
        public myTask() {
            super();
        }

        protected Void doInBackground(Void... params) {
            Api api = new Api("http://api.royaleapi.com/", devKey);
            Log.i("Debuga","startedBackground");
            profile = api.getProfile(ProfileRequest.builder("2PGGCJJL")
                    .keys(Arrays.asList("name", "clan", "tag"))
                    .excludes(Arrays.asList("battles"))
                    .build()
            );
            Log.i("Debuga","doneProfile");
            return null;
        }

        @Override
        protected void onPostExecute(Void result) {
            //do stuff
            Log.i("Debuga","postExecuteTask");
            Log.i("Debuga","profile: "+profile.getName());
        }
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Log.i("Debuga","start");
        new myTask().execute();
    }
}
```

If you want to check out the full project here it is:
https://mega.nz/#!fI5CwQYL!zVBXWEawlUHvo_o-QQJCffQTLlyQ0s6uBCvuiFnmw3U

**Comment by theagos** [comment]
Hey buddy..... i downloaded your code and works fine. Maybe, you must get another devKey because with my, your code work perfectly.

**Comment by Guiaki** [comment]
Its working again, I really don't understand what happened, but its not trustworthy, it might have been something to do with RoyaleAPI, dunno.

**Comment by mlieshoff** [comment]
You should check the logs and debug to find out, what royalapi returns in that case. Also check the status in discord, maybe they had an issue. So, I will close the issue.
