### ISSUE TITLE
games.wardaywins

### ISSUE THREAD

**Issue by theagos** [mlieshoff/jcrapi#89]
how can i get this end point?
I tried get profile.games and i got:
games=Games{total=2165, tournamentGames=0, wins=831, winsPercent=0.384, losses=941, lossesPercent=0.435, draws=393, drawsPercent=0.182, lastBattle=null}

**Comment by mlieshoff** [comment]
please see here: https://github.com/mlieshoff/jcrapi/issues/91

**Comment by mlieshoff** [comment]
done
